# Generated by Django 4.0.3 on 2022-03-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partclassworkflowcompletedtransition',
            name='notifying_next_user',
            field=models.BooleanField(default=True, verbose_name='Notifying next user'),
        ),
    ]
