# Generated by Django 4.0.3 on 2022-04-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0002_partclassworkflowcompletedtransition_notifying_next_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partclassworkflowstate',
            old_name='assigned_user',
            new_name='assigned_users',
        ),
    ]
