# Generated by Django 4.0.3 on 2022-04-12 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bom', '0003_rename_assigned_user_partclassworkflowstate_assigned_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partclassworkflowstate',
            name='assigned_users',
        ),
        migrations.AddField(
            model_name='partclassworkflowstate',
            name='assigned_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
