# Generated by Django 4.0.3 on 2022-04-12 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0004_remove_partclassworkflowstate_assigned_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partclassworkflowcompletedtransition',
            old_name='notifying_next_user',
            new_name='notifying_next_users',
        ),
    ]
