# Generated by Django 4.0.3 on 2022-04-14 02:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bom', '0006_alter_partclassworkflowcompletedtransition_notifying_next_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='partworkflowinstance',
            name='currently_assigned_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
