# Generated by Django 4.0.3 on 2022-04-14 02:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bom', '0008_alter_partworkflowinstance_currently_assigned_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partworkflowinstance',
            name='currently_assigned_users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
