# Generated by Django 3.2.13 on 2022-04-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0009_alter_partworkflowinstance_currently_assigned_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpart',
            name='alternatives',
            field=models.ManyToManyField(to='bom.PartRevision'),
        ),
    ]
