# Generated by Django 3.2.13 on 2022-04-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0010_subpart_alternatives'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subpart',
            old_name='alternatives',
            new_name='alternates',
        ),
    ]
