# Generated by Django 3.2.13 on 2022-04-28 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bom', '0011_rename_alternatives_subpart_alternates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partclassworkflowcompletedtransition',
            name='completed_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
