# Generated by Django 3.2.13 on 2022-05-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0046_alter_organization_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='partclassworkflow',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
