# Generated by Django 3.2.13 on 2022-06-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0047_partclassworkflow_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='partclassworkflowstate',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
